import type { AppSettings } from '@shared/types'

/** Default settings for component tests; mirrors the main-process DEFAULTS
    (electron/modules/settingsSchema.ts) without crossing the tsconfig boundary. */
export const TEST_SETTINGS: AppSettings = {
  watchFolders: [],
  downloadFolder: '',
  downloadQuality: 'mp3-320',
  downloadConcurrency: 5,
  autoFixYoutubeMetadata: true,
  crossfadeSeconds: 0,
  audioOffloadEnabled: false,
  replayGainEnabled: false,
  replayGainTargetDb: -18,
  eqEnabled: false,
  eqGains: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  eqCustomPresets: [],
  theme: 'dark',
  skin: 'plain',
  language: 'it',
  volume: 0.8,
  muted: false,
  notificationsOnTrackChange: true,
  globalMediaKeys: true,
  hasSeenOnboarding: false,
  spotifyClientId: '',
  spotifyClientSecret: '',
  lastfmApiKey: '',
  lastfmApiSecret: '',
  lastfmSessionKey: '',
  lastfmUsername: '',
  scrobblingEnabled: false,
  acoustidApiKey: '',
  autoEnrichEnabled: true,
  enrichFingerprint: true,
  dedupeAutoRemove: true,
  dedupeKeep: 'higher',
  googleClientId: '',
  googleClientSecret: '',
  driveSyncEnabled: false,
  driveSyncLastAt: null,
  googleDriveEmail: '',
  syncDeviceId: '',
  driveFileId: null,
  driveLastLocalHash: null,
  driveLastRemoteMd5: null,
  googleRefreshToken: '',
  autoFetchMissing: true,
  autoFetchNetwork: 'wifi',
  transferServerEnabled: false
}
